// Code generated by ogen, DO NOT EDIT.
package api

type CreateUserRes interface {
	createUserRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type GetUserByEmailRes interface {
	getUserByEmailRes()
}

type GetUserByIDRes interface {
	getUserByIDRes()
}

type GetUserByUsernameRes interface {
	getUserByUsernameRes()
}

type GetUserSubscriptionRes interface {
	getUserSubscriptionRes()
}

type UpdateUserRes interface {
	updateUserRes()
}
