// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelUserSubscription implements cancelUserSubscription operation.
	//
	// Cancel user subscription.
	//
	// PUT /user/subscription/cancel
	CancelUserSubscription(ctx context.Context) (CancelUserSubscriptionRes, error)
	// CreateUser implements createUser operation.
	//
	// Create a new user account.
	//
	// POST /user
	CreateUser(ctx context.Context, req *CreateUserReq) (CreateUserRes, error)
	// DeleteUser implements deleteUser operation.
	//
	// Delete user.
	//
	// DELETE /user
	DeleteUser(ctx context.Context) (DeleteUserRes, error)
	// GetUserByEmail implements getUserByEmail operation.
	//
	// Get user by email.
	//
	// GET /user/email/{email}
	GetUserByEmail(ctx context.Context, params GetUserByEmailParams) (GetUserByEmailRes, error)
	// GetUserByID implements getUserByID operation.
	//
	// Get user by ID.
	//
	// GET /user
	GetUserByID(ctx context.Context) (GetUserByIDRes, error)
	// GetUserByUsername implements getUserByUsername operation.
	//
	// Get user by username.
	//
	// GET /user/username/{username}
	GetUserByUsername(ctx context.Context, params GetUserByUsernameParams) (GetUserByUsernameRes, error)
	// GetUserSettings implements getUserSettings operation.
	//
	// Get user settings.
	//
	// GET /user/settings
	GetUserSettings(ctx context.Context) (GetUserSettingsRes, error)
	// GetUserStats implements getUserStats operation.
	//
	// Get user stats.
	//
	// GET /user/stats
	GetUserStats(ctx context.Context) (GetUserStatsRes, error)
	// GetUserSubscription implements getUserSubscription operation.
	//
	// Get user subscription.
	//
	// GET /user/subscription
	GetUserSubscription(ctx context.Context) (GetUserSubscriptionRes, error)
	// Login implements login operation.
	//
	// Login.
	//
	// POST /auth/login
	Login(ctx context.Context, req *LoginReq) (LoginRes, error)
	// StartUserTrial implements startUserTrial operation.
	//
	// Start user trial.
	//
	// PUT /user/subscription/trial
	StartUserTrial(ctx context.Context) (StartUserTrialRes, error)
	// UpdateUser implements updateUser operation.
	//
	// Update user.
	//
	// PUT /user
	UpdateUser(ctx context.Context, req *UpdateUserReq) (UpdateUserRes, error)
	// UpdateUserBodyMetrics implements updateUserBodyMetrics operation.
	//
	// Update user body metrics.
	//
	// PUT /user/stats/body
	UpdateUserBodyMetrics(ctx context.Context, req *UpdateUserBodyMetricsReq) (UpdateUserBodyMetricsRes, error)
	// UpdateUserRecordPayment implements updateUserRecordPayment operation.
	//
	// Update user record payment.
	//
	// PUT /user/subscription/payment
	UpdateUserRecordPayment(ctx context.Context, params UpdateUserRecordPaymentParams) (UpdateUserRecordPaymentRes, error)
	// UpdateUserSettings implements updateUserSettings operation.
	//
	// Update user settings.
	//
	// PUT /user/settings
	UpdateUserSettings(ctx context.Context, req *UpdateUserSettingsReq) (UpdateUserSettingsRes, error)
	// UpgradeUserPlan implements upgradeUserPlan operation.
	//
	// Upgrade user plan.
	//
	// PUT /user/subscription/plan
	UpgradeUserPlan(ctx context.Context, req *UpgradeUserPlanReq) (UpgradeUserPlanRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
