// Code generated by ogen, DO NOT EDIT.
package api

type CreateUserRes interface {
	createUserRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type GetUserByEmailRes interface {
	getUserByEmailRes()
}

type GetUserByIDRes interface {
	getUserByIDRes()
}

type GetUserByUsernameRes interface {
	getUserByUsernameRes()
}

type GetUserSettingsRes interface {
	getUserSettingsRes()
}

type GetUserStatsRes interface {
	getUserStatsRes()
}

type GetUserSubscriptionRes interface {
	getUserSubscriptionRes()
}

type UpdateUserBodyMetricsRes interface {
	updateUserBodyMetricsRes()
}

type UpdateUserRes interface {
	updateUserRes()
}

type UpdateUserSettingsRes interface {
	updateUserSettingsRes()
}
