// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CancelUserSubscription implements cancelUserSubscription operation.
//
// Cancel user subscription.
//
// PUT /user/subscription/cancel
func (UnimplementedHandler) CancelUserSubscription(ctx context.Context) (r CancelUserSubscriptionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateUser implements createUser operation.
//
// Create a new user account.
//
// POST /user
func (UnimplementedHandler) CreateUser(ctx context.Context, req *CreateUserReq) (r CreateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteUser implements deleteUser operation.
//
// Delete user.
//
// DELETE /user
func (UnimplementedHandler) DeleteUser(ctx context.Context) (r DeleteUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserByEmail implements getUserByEmail operation.
//
// Get user by email.
//
// GET /user/email/{email}
func (UnimplementedHandler) GetUserByEmail(ctx context.Context, params GetUserByEmailParams) (r GetUserByEmailRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserByID implements getUserByID operation.
//
// Get user by ID.
//
// GET /user
func (UnimplementedHandler) GetUserByID(ctx context.Context) (r GetUserByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserByUsername implements getUserByUsername operation.
//
// Get user by username.
//
// GET /user/username/{username}
func (UnimplementedHandler) GetUserByUsername(ctx context.Context, params GetUserByUsernameParams) (r GetUserByUsernameRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserSettings implements getUserSettings operation.
//
// Get user settings.
//
// GET /user/settings
func (UnimplementedHandler) GetUserSettings(ctx context.Context) (r GetUserSettingsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserStats implements getUserStats operation.
//
// Get user stats.
//
// GET /user/stats
func (UnimplementedHandler) GetUserStats(ctx context.Context) (r GetUserStatsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserSubscription implements getUserSubscription operation.
//
// Get user subscription.
//
// GET /user/subscription
func (UnimplementedHandler) GetUserSubscription(ctx context.Context) (r GetUserSubscriptionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Login implements login operation.
//
// Login.
//
// POST /auth/login
func (UnimplementedHandler) Login(ctx context.Context, req *LoginReq) (r LoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StartUserTrial implements startUserTrial operation.
//
// Start user trial.
//
// PUT /user/subscription/trial
func (UnimplementedHandler) StartUserTrial(ctx context.Context) (r StartUserTrialRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateUser implements updateUser operation.
//
// Update user.
//
// PUT /user
func (UnimplementedHandler) UpdateUser(ctx context.Context, req *UpdateUserReq) (r UpdateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateUserBodyMetrics implements updateUserBodyMetrics operation.
//
// Update user body metrics.
//
// PUT /user/stats/body
func (UnimplementedHandler) UpdateUserBodyMetrics(ctx context.Context, req *UpdateUserBodyMetricsReq) (r UpdateUserBodyMetricsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateUserRecordPayment implements updateUserRecordPayment operation.
//
// Update user record payment.
//
// PUT /user/subscription/payment
func (UnimplementedHandler) UpdateUserRecordPayment(ctx context.Context, params UpdateUserRecordPaymentParams) (r UpdateUserRecordPaymentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateUserSettings implements updateUserSettings operation.
//
// Update user settings.
//
// PUT /user/settings
func (UnimplementedHandler) UpdateUserSettings(ctx context.Context, req *UpdateUserSettingsReq) (r UpdateUserSettingsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpgradeUserPlan implements upgradeUserPlan operation.
//
// Upgrade user plan.
//
// PUT /user/subscription/plan
func (UnimplementedHandler) UpgradeUserPlan(ctx context.Context, req *UpgradeUserPlanReq) (r UpgradeUserPlanRes, _ error) {
	return r, ht.ErrNotImplemented
}
