// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelUserSubscription implements cancelUserSubscription operation.
	//
	// Cancel user subscription.
	//
	// PUT /user/{id}/subscription/cancel
	CancelUserSubscription(ctx context.Context, params CancelUserSubscriptionParams) (CancelUserSubscriptionRes, error)
	// CreateUser implements createUser operation.
	//
	// Create a new user account.
	//
	// POST /user
	CreateUser(ctx context.Context, req *CreateUserReq) (CreateUserRes, error)
	// DeleteUser implements deleteUser operation.
	//
	// Delete user.
	//
	// DELETE /user/{id}
	DeleteUser(ctx context.Context, params DeleteUserParams) (DeleteUserRes, error)
	// GetUserByEmail implements getUserByEmail operation.
	//
	// Get user by email.
	//
	// GET /user/email/{email}
	GetUserByEmail(ctx context.Context, params GetUserByEmailParams) (GetUserByEmailRes, error)
	// GetUserByID implements getUserByID operation.
	//
	// Get user by ID.
	//
	// GET /user/{id}
	GetUserByID(ctx context.Context, params GetUserByIDParams) (GetUserByIDRes, error)
	// GetUserByUsername implements getUserByUsername operation.
	//
	// Get user by username.
	//
	// GET /user/username/{username}
	GetUserByUsername(ctx context.Context, params GetUserByUsernameParams) (GetUserByUsernameRes, error)
	// GetUserSettings implements getUserSettings operation.
	//
	// Get user settings.
	//
	// GET /user/{id}/settings
	GetUserSettings(ctx context.Context, params GetUserSettingsParams) (GetUserSettingsRes, error)
	// GetUserStats implements getUserStats operation.
	//
	// Get user stats.
	//
	// GET /user/{id}/stats
	GetUserStats(ctx context.Context, params GetUserStatsParams) (GetUserStatsRes, error)
	// GetUserSubscription implements getUserSubscription operation.
	//
	// Get user subscription.
	//
	// GET /user/{id}/subscription
	GetUserSubscription(ctx context.Context, params GetUserSubscriptionParams) (GetUserSubscriptionRes, error)
	// StartUserTrial implements startUserTrial operation.
	//
	// Start user trial.
	//
	// PUT /user/{id}/subscription/trial
	StartUserTrial(ctx context.Context, params StartUserTrialParams) (StartUserTrialRes, error)
	// UpdateUser implements updateUser operation.
	//
	// Update user.
	//
	// PUT /user/{id}
	UpdateUser(ctx context.Context, req *UpdateUserReq, params UpdateUserParams) (UpdateUserRes, error)
	// UpdateUserBodyMetrics implements updateUserBodyMetrics operation.
	//
	// Update user body metrics.
	//
	// PUT /user/{id}/stats/body
	UpdateUserBodyMetrics(ctx context.Context, req *UpdateUserBodyMetricsReq, params UpdateUserBodyMetricsParams) (UpdateUserBodyMetricsRes, error)
	// UpdateUserRecordPayment implements updateUserRecordPayment operation.
	//
	// Update user record payment.
	//
	// PUT /user/{id}/subscription/payment
	UpdateUserRecordPayment(ctx context.Context, req *UpdateUserRecordPaymentReq, params UpdateUserRecordPaymentParams) (UpdateUserRecordPaymentRes, error)
	// UpdateUserSettings implements updateUserSettings operation.
	//
	// Update user settings.
	//
	// PUT /user/{id}/settings
	UpdateUserSettings(ctx context.Context, req *UpdateUserSettingsReq, params UpdateUserSettingsParams) (UpdateUserSettingsRes, error)
	// UpgradeUserPlan implements upgradeUserPlan operation.
	//
	// Upgrade user plan.
	//
	// PUT /user/{id}/subscription/plan
	UpgradeUserPlan(ctx context.Context, req *UpgradeUserPlanReq, params UpgradeUserPlanParams) (UpgradeUserPlanRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
