// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetUserByEmailParams is parameters of getUserByEmail operation.
type GetUserByEmailParams struct {
	// User email.
	Email string
}

func unpackGetUserByEmailParams(packed middleware.Parameters) (params GetUserByEmailParams) {
	{
		key := middleware.ParameterKey{
			Name: "email",
			In:   "path",
		}
		params.Email = packed[key].(string)
	}
	return params
}

func decodeGetUserByEmailParams(args [1]string, argsEscaped bool, r *http.Request) (params GetUserByEmailParams, _ error) {
	// Decode path: email.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "email",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Email = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        true,
					Hostname:     false,
					Regex:        nil,
				}).Validate(string(params.Email)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "email",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetUserByUsernameParams is parameters of getUserByUsername operation.
type GetUserByUsernameParams struct {
	// Username.
	Username string
}

func unpackGetUserByUsernameParams(packed middleware.Parameters) (params GetUserByUsernameParams) {
	{
		key := middleware.ParameterKey{
			Name: "username",
			In:   "path",
		}
		params.Username = packed[key].(string)
	}
	return params
}

func decodeGetUserByUsernameParams(args [1]string, argsEscaped bool, r *http.Request) (params GetUserByUsernameParams, _ error) {
	// Decode path: username.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "username",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Username = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "username",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateUserRecordPaymentParams is parameters of updateUserRecordPayment operation.
type UpdateUserRecordPaymentParams struct {
	// User ID.
	ID uuid.UUID
}

func unpackUpdateUserRecordPaymentParams(packed middleware.Parameters) (params UpdateUserRecordPaymentParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeUpdateUserRecordPaymentParams(args [0]string, argsEscaped bool, r *http.Request) (params UpdateUserRecordPaymentParams, _ error) {
	// Decode path: id.
	if err := func() error {
		// Not used.
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
