// Code generated by ogen, DO NOT EDIT.
package api

type CancelUserSubscriptionRes interface {
	cancelUserSubscriptionRes()
}

type CreateUserRes interface {
	createUserRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type GetUserByEmailRes interface {
	getUserByEmailRes()
}

type GetUserByIDRes interface {
	getUserByIDRes()
}

type GetUserByUsernameRes interface {
	getUserByUsernameRes()
}

type GetUserSettingsRes interface {
	getUserSettingsRes()
}

type GetUserStatsRes interface {
	getUserStatsRes()
}

type GetUserSubscriptionRes interface {
	getUserSubscriptionRes()
}

type LoginRes interface {
	loginRes()
}

type StartUserTrialRes interface {
	startUserTrialRes()
}

type UpdateUserBodyMetricsRes interface {
	updateUserBodyMetricsRes()
}

type UpdateUserRecordPaymentRes interface {
	updateUserRecordPaymentRes()
}

type UpdateUserRes interface {
	updateUserRes()
}

type UpdateUserSettingsRes interface {
	updateUserSettingsRes()
}

type UpgradeUserPlanRes interface {
	upgradeUserPlanRes()
}
