// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateUserOperation        OperationName = "CreateUser"
	DeleteUserOperation        OperationName = "DeleteUser"
	GetUserByEmailOperation    OperationName = "GetUserByEmail"
	GetUserByIDOperation       OperationName = "GetUserByID"
	GetUserByUsernameOperation OperationName = "GetUserByUsername"
	ListUsersOperation         OperationName = "ListUsers"
	UpdateUserOperation        OperationName = "UpdateUser"
)
