// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CancelUserSubscriptionOperation  OperationName = "CancelUserSubscription"
	CreateUserOperation              OperationName = "CreateUser"
	DeleteUserOperation              OperationName = "DeleteUser"
	GetUserByEmailOperation          OperationName = "GetUserByEmail"
	GetUserByIDOperation             OperationName = "GetUserByID"
	GetUserByUsernameOperation       OperationName = "GetUserByUsername"
	GetUserSettingsOperation         OperationName = "GetUserSettings"
	GetUserStatsOperation            OperationName = "GetUserStats"
	GetUserSubscriptionOperation     OperationName = "GetUserSubscription"
	LoginOperation                   OperationName = "Login"
	StartUserTrialOperation          OperationName = "StartUserTrial"
	UpdateUserOperation              OperationName = "UpdateUser"
	UpdateUserBodyMetricsOperation   OperationName = "UpdateUserBodyMetrics"
	UpdateUserRecordPaymentOperation OperationName = "UpdateUserRecordPayment"
	UpdateUserSettingsOperation      OperationName = "UpdateUserSettings"
	UpgradeUserPlanOperation         OperationName = "UpgradeUserPlan"
)
